int LED1 = 8;
int LED2 = 9;
int LED3 = 10;
int shortBlink = 250; 
int avgBlink = 500;
int longBlink = 1000; 

void setup() {
  // put your setup code here, to run once:
  pinMode(LED1, OUTPUT); 
  pinMode(LED2, OUTPUT); 
  pinMode(LED3, OUTPUT); 
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(LED1, HIGH);
  delay(shortBlink);
  digitalWrite(LED1, LOW);
  delay(shortBlink);
  digitalWrite(LED1, HIGH);
  delay(shortBlink);
  digitalWrite(LED1, LOW);
  delay(shortBlink);
  digitalWrite(LED1, HIGH);
  delay(shortBlink);
  digitalWrite(LED1, LOW);
  delay(shortBlink);
  digitalWrite(LED1, HIGH);
  delay(shortBlink);
  digitalWrite(LED1, LOW);
  delay(shortBlink);
  digitalWrite(LED1, HIGH);
  delay(shortBlink);
  digitalWrite(LED1, LOW);
  delay(shortBlink);

  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);
  digitalWrite(LED2, HIGH);
  delay(avgBlink);
  digitalWrite(LED2, LOW);
  delay(avgBlink);

  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);
  digitalWrite(LED3, HIGH);
  delay(longBlink);
  digitalWrite(LED3, LOW);
  delay(longBlink);


}
